spring.application.name=payment-service

server.port=5007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/paymentdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=d@kshsql5R
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


razorpay.api.key="Your razorpay api key"
razorpay.api.secret="Your razorpay api secret"

stripe.api.key="Your stripe api key"
